import "./globals.css";
import type { Metadata } from "next";
import { Open_Sans, Caveat, Nanum_Gothic } from "next/font/google";
export const sans = Open_Sans({ subsets: ["latin"] });
export const gothic = Nanum_Gothic({
  weight: "400",
  subsets: ["latin"],
});
export const caveat = Caveat({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={sans.className}>{children}</body>
    </html>
  );
}
